spring.application.name=SpringOAuth2Demo

spring.security.oauth2.client.registration.google.client-id=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
spring.security.oauth2.client.registration.google.client-secret=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx