package com.naman.learning;

import java.io.IOException;
import java.io.PrintWriter;
import java.rmi.ServerException;

import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

@WebServlet("/firstServlet")
public class FirstServletApp extends HttpServlet {
    public FirstServletApp(){
        System.out.println("Servlet obj is created internally by container");
    }
    public void doPost(HttpServletRequest request, HttpServletResponse response) throws ServerException, IOException {
        String name = request.getParameter("uname");
        String city = request.getParameter("ucity");

        response.setContentType("text/html");

        PrintWriter out = response.getWriter();


        out.println("<!DOCTYPE html>");
        out.println("<html>");
        out.println("<head>");
        out.println("<title>Servlet Response</title>");
        out.println("<style>");
        out.println("body{");
        out.println("font-family:Arial,sans-serif;");
        out.println("background:#f4f4f4;");
        out.println("display:flex;");
        out.println("justify-content:center;");
        out.println("align-items:center;");
        out.println("height:100vh;");
        out.println("}");
        out.println(".card{");
        out.println("background:white;");
        out.println("padding:30px;");
        out.println("border-radius:10px;");
        out.println("box-shadow:0 0 10px rgba(0,0,0,0.2);");
        out.println("text-align:center;");
        out.println("}");
        out.println("h1{color:#0d6efd;}");
        out.println("p{font-size:18px;}");
        out.println("</style>");
        out.println("</head>");
        out.println("<body>");

        out.println("<div class='card'>");
        out.println("<h1>Welcome " + name + " 🎉</h1>");
        out.println("<p>Glad to know you're from <b>" + city + "</b>.</p>");
        out.println("<hr>");
        out.println("<h3>Dynamic Response Generated by Servlet</h3>");
        out.println("<p>Current Servlet: <b>FirstServletApp</b></p>");
        out.println("</div>");

        out.println("</body>");
        out.println("</html>");

        out.close();
    }
}
